version: '3.4'

services:
  main:
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetask
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask/Dockerfile

  identity:
    container_name: identity
    image: ${DOCKER_REGISTRY-}myidentityserver
    build:
      context: .
      dockerfile: MyIdentityServer/Dockerfile
      


