version: '3.4'

services:
  mongodb:
    container_name: data
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  
  main:
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetask
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask/Dockerfile
    depends_on:
      - mongodb
    networks:
      - app-network

  identity:
    container_name: identity
    image: ${DOCKER_REGISTRY-}myidentityserver
    build:
      context: .
      dockerfile: MyIdentityServer/Dockerfile
    networks:
      - app-network
      
      
volumes:
  mongodb_data:
    
networks:
  app-network:


