version: '3.4'

services:
  mongodb:
    container_name: data
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  
  main:
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetask
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask/Dockerfile
    depends_on:
      - mongodb
    networks:
      - app-network

  identity:
    container_name: identity
    image: ${DOCKER_REGISTRY-}myidentityserver
    build:
      context: .
      dockerfile: MyIdentityServer/Dockerfile
    networks:
      - app-network
      
      
  images:
    container_name: images
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetaskimages
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask.Images/Dockerfile
    networks:
      - app-network

  rooms:
    container_name: rooms
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetaskrooms
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask.Rooms/Dockerfile
    networks:
      - app-network

volumes:
  mongodb_data:
    
networks:
  app-network:


