version: '3.4'

services:
  mongodb:
    container_name: data
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  main:
    container_name: main
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetask
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    env_file:
      - ./SenseCapitalTraineeTask/env.list
    ports:
      - "29000:80"
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - app-network

  identity:
    container_name: identity
    image: ${DOCKER_REGISTRY-}myidentityserver
    build:
      context: .
      dockerfile: MyIdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: on-failure
    ports:
      - "28000:80"
    networks:
      - app-network
      
      
  images:
    container_name: images
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetaskimages
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask.Images/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    env_file:
      - ./SenseCapitalTraineeTask.Images/env.list
    ports:
      - "26000:80"
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rooms:
    container_name: rooms
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetaskrooms
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask.Rooms/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    env_file:
      - ./SenseCapitalTraineeTask.Rooms/env.list
    ports:
      - "25000:80"
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - app-network

  payment:
    container_name: payment
    image: ${DOCKER_REGISTRY-}sensecapitaltraineetaskpayment
    build:
      context: .
      dockerfile: SenseCapitalTraineeTask.Payment/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    env_file:
      - ./SenseCapitalTraineeTask.Payment/env.list
    ports:
      - "27000:80"
    restart: on-failure
    networks:
      - app-network

volumes:
  mongodb_data:
    
networks:
  app-network:


